version: "2"
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        image: gatsby-nginx
        ports:
            - 8080:8080
        volumes:
            - .:/app